In [1]:
import pandas as pd

In [73]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import cross_val_score
import pickle
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

In [3]:
from sklearn.preprocessing import StandardScaler

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
# Load a sample of the datasets to identify column names at indices 25 and 108
df = pd.read_csv('male_players (legacy).csv')
df2 = pd.read_csv('players_22.csv')

/tmp/ipykernel_1247/1996295060.py:2: DtypeWarning: Columns (108) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('male_players (legacy).csv')
/tmp/ipykernel_1247/1996295060.py:3: DtypeWarning: Columns (25,108) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('players_22.csv')

In [6]:
# Print column names at indices 25 and 108
legacy_column_25 = df.columns[25]
legacy_column_108 = df.columns[108]
players_22_column_25 = df2.columns[25]
players_22_column_108 = df2.columns[108]

In [7]:
print("Legacy Dataset Column 25:", legacy_column_25)
print("Legacy Dataset Column 108:", legacy_column_108)
print("Players 22 Dataset Column 25:", players_22_column_25)
print("Players 22 Dataset Column 108:", players_22_column_108)

Legacy Dataset Column 25: club_contract_valid_until_year
Legacy Dataset Column 108: gk
Players 22 Dataset Column 25: nation_position
Players 22 Dataset Column 108: nation_logo_url

In [8]:
# Define data types for columns with mixed types using column names
dtype_spec = {
    legacy_column_25: 'str',
    legacy_column_108: 'str',
    players_22_column_25: 'str',
    players_22_column_108: 'str'
}

In [9]:
#Loading the dataset given
df2 = pd.read_csv('players_22.csv',low_memory =False)#, dtype=dtype_spec) #player_22
df= pd.read_csv('male_players (legacy).csv',low_memory =False)#, dtype=dtype_spec) #male_legacy

In [10]:
df.head()

,player_id,player_url,fifa_version,fifa_update,fifa_update_date,short_name,long_name,player_positions,overall,potential,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url
0,158023,/player/158023/lionel-messi/150002,15,2,2014-09-18,L. Messi,Lionel Andrés Messi Cuccittini,CF,93,95,...,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,15+3,https://cdn.sofifa.net/players/158/023/15_120.png
1,20801,/player/20801/c-ronaldo-dos-santos-aveiro/150002,15,2,2014-09-18,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"LW, LM",92,92,...,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,16+3,https://cdn.sofifa.net/players/020/801/15_120.png
2,9014,/player/9014/arjen-robben/150002,15,2,2014-09-18,A. Robben,Arjen Robben,"RM, LM, RW",90,90,...,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,14+3,https://cdn.sofifa.net/players/009/014/15_120.png
3,41236,/player/41236/zlatan-ibrahimovic/150002,15,2,2014-09-18,Z. Ibrahimović,Zlatan Ibrahimović,ST,90,90,...,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,17+3,https://cdn.sofifa.net/players/041/236/15_120.png
4,167495,/player/167495/manuel-neuer/150002,15,2,2014-09-18,M. Neuer,Manuel Peter Neuer,GK,90,90,...,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,87+3,https://cdn.sofifa.net/players/167/495/15_120.png

In [11]:
df2.head()

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,...,50+3,50+3,50+3,61+3,19+3,https://cdn.sofifa.net/players/158/023/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,...,60+3,60+3,60+3,61+3,19+3,https://cdn.sofifa.net/players/188/545/22_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1353/60.png,https://cdn.sofifa.net/flags/pl.png
2,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,...,53+3,53+3,53+3,60+3,20+3,https://cdn.sofifa.net/players/020/801/22_120.png,https://cdn.sofifa.net/teams/11/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
3,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",91,91,129000000.0,270000.0,29,...,50+3,50+3,50+3,62+3,20+3,https://cdn.sofifa.net/players/190/871/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,NaN,https://cdn.sofifa.net/flags/br.png
4,192985,https://sofifa.com/player/192985/kevin-de-bruy...,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,...,69+3,69+3,69+3,75+3,21+3,https://cdn.sofifa.net/players/192/985/22_120.png,https://cdn.sofifa.net/teams/10/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1325/60.png,https://cdn.sofifa.net/flags/be.png

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161583 entries, 0 to 161582
Columns: 110 entries, player_id to player_face_url
dtypes: float64(18), int64(45), object(47)
memory usage: 135.6+ MB

In [13]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19239 entries, 0 to 19238
Columns: 110 entries, sofifa_id to nation_flag_url
dtypes: float64(16), int64(44), object(50)
memory usage: 16.1+ MB

In [14]:
# Inspect the shape of the datasets
print("Training data shape:", df.shape)
print("Test data shape:", df2.shape)

# Inspect missing values in the datasets
print("Missing values in training data:\n", df.isnull().sum())
print("Missing values in test data:\n", df2.isnull().sum())

Training data shape: (161583, 110)
Test data shape: (19239, 110)
Missing values in training data:
 player_id           0
player_url          0
fifa_version        0
fifa_update         0
fifa_update_date    0
                   ..
cb                  0
rcb                 0
rb                  0
gk                  0
player_face_url     0
Length: 110, dtype: int64
Missing values in test data:
 sofifa_id               0
player_url              0
short_name              0
long_name               0
player_positions        0
                    ...
player_face_url         0
club_logo_url          61
club_flag_url          61
nation_logo_url     18480
nation_flag_url         0
Length: 110, dtype: int64

In [15]:
missing_percent = df.isnull().sum() / len(df)

# Display the percentage of missing data
print(missing_percent)

# Drop columns with more than 30% missing values
threshold = 0.30
columns_to_drop = missing_percent[missing_percent > threshold].index

df = df.drop(columns=columns_to_drop)

# Display the cleaned DataFrame
df.head()

player_id           0.0
player_url          0.0
fifa_version        0.0
fifa_update         0.0
fifa_update_date    0.0
                   ...
cb                  0.0
rcb                 0.0
rb                  0.0
gk                  0.0
player_face_url     0.0
Length: 110, dtype: float64

,player_id,player_url,fifa_version,fifa_update,fifa_update_date,short_name,long_name,player_positions,overall,potential,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url
0,158023,/player/158023/lionel-messi/150002,15,2,2014-09-18,L. Messi,Lionel Andrés Messi Cuccittini,CF,93,95,...,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,15+3,https://cdn.sofifa.net/players/158/023/15_120.png
1,20801,/player/20801/c-ronaldo-dos-santos-aveiro/150002,15,2,2014-09-18,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"LW, LM",92,92,...,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,16+3,https://cdn.sofifa.net/players/020/801/15_120.png
2,9014,/player/9014/arjen-robben/150002,15,2,2014-09-18,A. Robben,Arjen Robben,"RM, LM, RW",90,90,...,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,14+3,https://cdn.sofifa.net/players/009/014/15_120.png
3,41236,/player/41236/zlatan-ibrahimovic/150002,15,2,2014-09-18,Z. Ibrahimović,Zlatan Ibrahimović,ST,90,90,...,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,17+3,https://cdn.sofifa.net/players/041/236/15_120.png
4,167495,/player/167495/manuel-neuer/150002,15,2,2014-09-18,M. Neuer,Manuel Peter Neuer,GK,90,90,...,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,87+3,https://cdn.sofifa.net/players/167/495/15_120.png

In [16]:
df.dtypes

player_id            int64
player_url          object
fifa_version         int64
fifa_update          int64
fifa_update_date    object
                     ...
cb                  object
rcb                 object
rb                  object
gk                  object
player_face_url     object
Length: 102, dtype: object

In [17]:
#drop things that be useless
df.columns

Index(['player_id', 'player_url', 'fifa_version', 'fifa_update',
       'fifa_update_date', 'short_name', 'long_name', 'player_positions',
       'overall', 'potential',
       ...
       'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk',
       'player_face_url'],
      dtype='object', length=102)

In [18]:
df.drop(columns = ['player_id', 'player_url', 'fifa_version', 'fifa_update', 'fifa_update_date', 'player_face_url', 'short_name', 'long_name'], inplace = True)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161583 entries, 0 to 161582
Data columns (total 94 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   player_positions                161583 non-null  object
 1   overall                         161583 non-null  int64
 2   potential                       161583 non-null  int64
 3   value_eur                       159530 non-null  float64
 4   wage_eur                        159822 non-null  float64
 5   age                             161583 non-null  int64
 6   dob                             161583 non-null  object
 7   height_cm                       161583 non-null  int64
 8   weight_kg                       161583 non-null  int64
 9   league_id                       159810 non-null  float64
 10  league_name                     159810 non-null  object
 11  league_level                    158866 non-null  float64
 12  club_team_id                    159810 non-null  float64
 13  club_name                       159810 non-null  object
 14  club_position                   159810 non-null  object
 15  club_jersey_number              159810 non-null  float64
 16  club_joined_date                150272 non-null  object
 17  club_contract_valid_until_year  159810 non-null  float64
 18  nationality_id                  161583 non-null  int64
 19  nationality_name                161583 non-null  object
 20  preferred_foot                  161583 non-null  object
 21  weak_foot                       161583 non-null  int64
 22  skill_moves                     161583 non-null  int64
 23  international_reputation        161583 non-null  int64
 24  work_rate                       161583 non-null  object
 25  body_type                       161583 non-null  object
 26  real_face                       161583 non-null  object
 27  pace                            143614 non-null  float64
 28  shooting                        143614 non-null  float64
 29  passing                         143614 non-null  float64
 30  dribbling                       143614 non-null  float64
 31  defending                       143614 non-null  float64
 32  physic                          143614 non-null  float64
 33  attacking_crossing              161583 non-null  int64
 34  attacking_finishing             161583 non-null  int64
 35  attacking_heading_accuracy      161583 non-null  int64
 36  attacking_short_passing         161583 non-null  int64
 37  attacking_volleys               161583 non-null  int64
 38  skill_dribbling                 161583 non-null  int64
 39  skill_curve                     161583 non-null  int64
 40  skill_fk_accuracy               161583 non-null  int64
 41  skill_long_passing              161583 non-null  int64
 42  skill_ball_control              161583 non-null  int64
 43  movement_acceleration           161583 non-null  int64
 44  movement_sprint_speed           161583 non-null  int64
 45  movement_agility                161583 non-null  int64
 46  movement_reactions              161583 non-null  int64
 47  movement_balance                161583 non-null  int64
 48  power_shot_power                161583 non-null  int64
 49  power_jumping                   161583 non-null  int64
 50  power_stamina                   161583 non-null  int64
 51  power_strength                  161583 non-null  int64
 52  power_long_shots                161583 non-null  int64
 53  mentality_aggression            161583 non-null  int64
 54  mentality_interceptions         161583 non-null  int64
 55  mentality_positioning           161583 non-null  int64
 56  mentality_vision                161583 non-null  int64
 57  mentality_penalties             161583 non-null  int64
 58  mentality_composure             128722 non-null  float64
 59  defending_marking_awareness     161583 non-null  int64
 60  defending_standing_tackle       161583 non-null  int64
 61  defending_sliding_tackle        161583 non-null  int64
 62  goalkeeping_diving              161583 non-null  int64
 63  goalkeeping_handling            161583 non-null  int64
 64  goalkeeping_kicking             161583 non-null  int64
 65  goalkeeping_positioning         161583 non-null  int64
 66  goalkeeping_reflexes            161583 non-null  int64
 67  ls                              161583 non-null  object
 68  st                              161583 non-null  object
 69  rs                              161583 non-null  object
 70  lw                              161583 non-null  object
 71  lf                              161583 non-null  object
 72  cf                              161583 non-null  object
 73  rf                              161583 non-null  object
 74  rw                              161583 non-null  object
 75  lam                             161583 non-null  object
 76  cam                             161583 non-null  object
 77  ram                             161583 non-null  object
 78  lm                              161583 non-null  object
 79  lcm                             161583 non-null  object
 80  cm                              161583 non-null  object
 81  rcm                             161583 non-null  object
 82  rm                              161583 non-null  object
 83  lwb                             161583 non-null  object
 84  ldm                             161583 non-null  object
 85  cdm                             161583 non-null  object
 86  rdm                             161583 non-null  object
 87  rwb                             161583 non-null  object
 88  lb                              161583 non-null  object
 89  lcb                             161583 non-null  object
 90  cb                              161583 non-null  object
 91  rcb                             161583 non-null  object
 92  rb                              161583 non-null  object
 93  gk                              161583 non-null  object
dtypes: float64(14), int64(42), object(38)
memory usage: 115.9+ MB

In [20]:
df.head()

,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,league_id,...,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk
0,CF,93,95,100500000.0,550000.0,27,1987-06-24,169,67,53.0,...,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3,15+3
1,"LW, LM",92,92,79000000.0,375000.0,29,1985-02-05,185,80,53.0,...,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3,16+3
2,"RM, LM, RW",90,90,54500000.0,275000.0,30,1984-01-23,180,80,19.0,...,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3,14+3
3,ST,90,90,52500000.0,275000.0,32,1981-10-03,195,95,16.0,...,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3,17+3
4,GK,90,90,63500000.0,300000.0,28,1986-03-27,193,92,19.0,...,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3,87+3

# PROCESSING QUANTITATIVE DATA

In [22]:
Quantitative = df.select_dtypes(include=[np.number])
corr_matrix = Quantitative.corr()
columns_to_drop = [column for column in Quantitative.columns if abs(corr_matrix['overall'][column]) < 0.4]
Quantitative.drop(columns=columns_to_drop, axis=1, inplace=True)
corr_matrix['overall'].sort_values(ascending=False)
Quantitative.columns

Index(['overall', 'potential', 'value_eur', 'wage_eur', 'age',
       'international_reputation', 'shooting', 'passing', 'dribbling',
       'physic', 'attacking_short_passing', 'skill_curve',
       'skill_long_passing', 'skill_ball_control', 'movement_reactions',
       'power_shot_power', 'power_long_shots', 'mentality_vision',
       'mentality_composure'],
      dtype='object')

In [23]:
important_cols = ['body_type', 'preferred_foot']
Categorical = df.select_dtypes(include = ['object'])
Categorical.drop(columns = [column for column in Categorical.columns if column not in important_cols], inplace =True)
Categorical.columns

Index(['preferred_foot', 'body_type'], dtype='object')

In [24]:
QuantandCat = pd.concat([Categorical, Quantitative], axis = 1)
QuantandCat.columns

Index(['preferred_foot', 'body_type', 'overall', 'potential', 'value_eur',
       'wage_eur', 'age', 'international_reputation', 'shooting', 'passing',
       'dribbling', 'physic', 'attacking_short_passing', 'skill_curve',
       'skill_long_passing', 'skill_ball_control', 'movement_reactions',
       'power_shot_power', 'power_long_shots', 'mentality_vision',
       'mentality_composure'],
      dtype='object')

In [25]:
y = df['overall'] #our target variable

In [26]:
quant = df.select_dtypes(include = [np.number]) #we get all the quantitative features

In [27]:
corr_matrix = quant.corr()

In [28]:
corr_matrix['overall'].sort_values(ascending = False)

overall                           1.000000
movement_reactions                0.845753
potential                         0.695362
mentality_composure               0.683307
passing                           0.681114
wage_eur                          0.611368
dribbling                         0.606575
value_eur                         0.566827
physic                            0.513279
attacking_short_passing           0.499757
mentality_vision                  0.493282
international_reputation          0.485234
skill_long_passing                0.483808
shooting                          0.482498
power_shot_power                  0.480297
age                               0.458390
skill_ball_control                0.457011
skill_curve                       0.415863
power_long_shots                  0.409086
mentality_aggression              0.398310
attacking_crossing                0.396833
skill_fk_accuracy                 0.387269
attacking_volleys                 0.377048
skill_dribbling                   0.369827
power_stamina                     0.360025
power_strength                    0.350786
mentality_positioning             0.350178
attacking_heading_accuracy        0.340029
mentality_penalties               0.334488
skill_moves                       0.330951
attacking_finishing               0.326376
defending                         0.325151
mentality_interceptions           0.314282
power_jumping                     0.275578
defending_marking_awareness       0.274173
movement_agility                  0.263671
defending_standing_tackle         0.250624
defending_sliding_tackle          0.220398
weak_foot                         0.217422
movement_sprint_speed             0.208990
movement_acceleration             0.194625
pace                              0.187184
weight_kg                         0.140015
movement_balance                  0.099129
club_contract_valid_until_year    0.072073
height_cm                         0.044415
goalkeeping_positioning          -0.004731
goalkeeping_handling             -0.010862
goalkeeping_reflexes             -0.011783
goalkeeping_diving               -0.013603
goalkeeping_kicking              -0.015521
nationality_id                   -0.093951
league_id                        -0.152280
club_team_id                     -0.178272
club_jersey_number               -0.187109
league_level                     -0.221734
Name: overall, dtype: float64

In [29]:
#we are dropping columns that have a correlation less than 0.4 and greater than -0.4
for column in quant.columns:
  if corr_matrix['overall'][column] < 0.4 and corr_matrix['overall'][column] > -0.4:
    quant.drop(column, axis = 1, inplace = True)

In [30]:
quant.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161583 entries, 0 to 161582
Data columns (total 19 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   overall                   161583 non-null  int64
 1   potential                 161583 non-null  int64
 2   value_eur                 159530 non-null  float64
 3   wage_eur                  159822 non-null  float64
 4   age                       161583 non-null  int64
 5   international_reputation  161583 non-null  int64
 6   shooting                  143614 non-null  float64
 7   passing                   143614 non-null  float64
 8   dribbling                 143614 non-null  float64
 9   physic                    143614 non-null  float64
 10  attacking_short_passing   161583 non-null  int64
 11  skill_curve               161583 non-null  int64
 12  skill_long_passing        161583 non-null  int64
 13  skill_ball_control        161583 non-null  int64
 14  movement_reactions        161583 non-null  int64
 15  power_shot_power          161583 non-null  int64
 16  power_long_shots          161583 non-null  int64
 17  mentality_vision          161583 non-null  int64
 18  mentality_composure       128722 non-null  float64
dtypes: float64(7), int64(12)
memory usage: 23.4 MB

In [31]:
corr_matrix = quant.corr()

In [32]:
corr_matrix['overall'].sort_values(ascending = False)

overall                     1.000000
movement_reactions          0.845753
potential                   0.695362
mentality_composure         0.683307
passing                     0.681114
wage_eur                    0.611368
dribbling                   0.606575
value_eur                   0.566827
physic                      0.513279
attacking_short_passing     0.499757
mentality_vision            0.493282
international_reputation    0.485234
skill_long_passing          0.483808
shooting                    0.482498
power_shot_power            0.480297
age                         0.458390
skill_ball_control          0.457011
skill_curve                 0.415863
power_long_shots            0.409086
Name: overall, dtype: float64

In [75]:
#we need to impute cause there are missing values
imputer = SimpleImputer(strategy = 'median')
q_columns = quant.columns
quant = imputer.fit_transform(quant)
quant = pd.DataFrame(quant, columns = q_columns)

In [76]:
quant

,overall,potential,value_eur,wage_eur,age,international_reputation,shooting,passing,dribbling,physic,attacking_short_passing,skill_curve,skill_long_passing,skill_ball_control,movement_reactions,power_shot_power,power_long_shots,mentality_vision,mentality_composure
0,93.0,95.0,100500000.0,550000.0,27.0,5.0,89.0,86.0,96.0,63.0,89.0,89.0,76.0,96.0,94.0,80.0,88.0,90.0,59.0
1,92.0,92.0,79000000.0,375000.0,29.0,5.0,93.0,81.0,91.0,79.0,82.0,88.0,72.0,92.0,90.0,94.0,93.0,81.0,59.0
2,90.0,90.0,54500000.0,275000.0,30.0,5.0,86.0,83.0,92.0,64.0,86.0,85.0,76.0,90.0,89.0,86.0,90.0,84.0,59.0
3,90.0,90.0,52500000.0,275000.0,32.0,5.0,91.0,81.0,86.0,86.0,84.0,80.0,76.0,90.0,85.0,93.0,88.0,83.0,59.0
4,90.0,90.0,63500000.0,300000.0,28.0,5.0,54.0,58.0,63.0,66.0,42.0,25.0,41.0,31.0,89.0,42.0,25.0,20.0,59.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161578,46.0,61.0,110000.0,700.0,18.0,1.0,48.0,40.0,47.0,44.0,38.0,39.0,33.0,45.0,39.0,64.0,31.0,42.0,40.0
161579,46.0,58.0,110000.0,750.0,19.0,1.0,25.0,29.0,34.0,57.0,30.0,24.0,25.0,32.0,42.0,33.0,25.0,31.0,35.0
161580,46.0,58.0,110000.0,500.0,19.0,1.0,36.0,43.0,46.0,53.0,51.0,30.0,43.0,35.0,50.0,51.0,32.0,40.0,35.0
161581,46.0,70.0,150000.0,500.0,17.0,1.0,50.0,36.0,46.0,42.0,40.0,38.0,26.0,43.0,45.0,42.0,47.0,44.0,43.0
161582,46.0,63.0,110000.0,500.0,17.0,1.0,22.0,26.0,32.0,57.0,32.0,21.0,29.0,31.0,40.0,33.0,20.0,20.0,30.0

In [81]:
#after imputing then we need to scale
scaler = StandardScaler()
quant = pd.DataFrame(scaler.fit_transform(quant), columns = quant.columns)
quant

,overall,potential,value_eur,wage_eur,age,international_reputation,shooting,passing,dribbling,physic,attacking_short_passing,skill_curve,skill_long_passing,skill_ball_control,movement_reactions,power_shot_power,power_long_shots,mentality_vision,mentality_composure
0,3.877514,3.875315,16.447428,24.697104,0.401872,10.148137,2.783978,2.926570,3.480487,-0.211839,2.086204,2.306588,1.536683,2.281310,3.535775,1.499832,2.148684,2.588430,0.085565
1,3.735485,3.396013,12.846177,16.681825,0.830120,10.148137,3.088467,2.421008,2.965866,1.529711,1.609554,2.251267,1.273977,2.039859,3.099571,2.401757,2.411698,1.957672,0.085565
2,3.451428,3.076478,8.742427,12.101666,1.044244,10.148137,2.555612,2.623233,3.068791,-0.102992,1.881925,2.085305,1.536683,1.919133,2.990520,1.886371,2.253890,2.167924,0.085565
3,3.451428,3.076478,8.407427,12.101666,1.472491,10.148137,2.936223,2.421008,2.451245,2.291639,1.745740,1.808701,1.536683,1.919133,2.554317,2.337334,2.148684,2.097840,0.085565
4,3.451428,3.076478,10.249927,13.246706,0.615996,10.148137,0.119701,0.095424,0.083989,0.114701,-1.114157,-1.233943,-0.761996,-1.642271,2.990520,-0.948252,-1.165296,-2.317466,0.085565
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161578,-2.797832,-1.556774,-0.367900,-0.461712,-1.525244,-0.279299,-0.337032,-1.724598,-1.562798,-2.279930,-1.386528,-0.459452,-1.287408,-0.797192,-2.462022,0.469059,-0.849678,-0.775613,-1.639346
161579,-2.797832,-2.036076,-0.367900,-0.459422,-1.311120,-0.279299,-2.087843,-2.836834,-2.900813,-0.864920,-1.931270,-1.289264,-1.812820,-1.581909,-2.134869,-1.528062,-1.165296,-1.546539,-2.093270
161580,-2.797832,-2.036076,-0.367900,-0.470872,-1.311120,-0.279299,-1.250499,-1.421261,-1.665723,-1.300308,-0.501322,-0.957339,-0.630643,-1.400820,-1.262462,-0.368443,-0.797076,-0.915781,-2.093270
161581,-2.797832,-0.118868,-0.361200,-0.470872,-1.739368,-0.279299,-0.184788,-2.129048,-1.665723,-2.497623,-1.250342,-0.514773,-1.747144,-0.917918,-1.807717,-0.948252,-0.008033,-0.635445,-1.366992
161582,-2.797832,-1.237239,-0.367900,-0.470872,-1.739368,-0.279299,-2.316209,-3.140171,-3.106661,-0.864920,-1.795084,-1.455227,-1.550114,-1.642271,-2.352971,-1.528062,-1.428310,-2.317466,-2.547194

In [85]:
quant.drop('overall', axis = 1, inplace = True)

In [87]:
# common relevant columns present in both datasets
relevant_columns = [col for col in Quantitative if col in df.columns and col in df2.columns]

# Extracting features and target variable from the training data
X = df[relevant_columns]
Y = df['overall']

# PROCESSING CATEGORICAL DATA

In [89]:
cat = df.select_dtypes(include = ['object'])
cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161583 entries, 0 to 161582
Data columns (total 38 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   player_positions  161583 non-null  object
 1   dob               161583 non-null  object
 2   league_name       159810 non-null  object
 3   club_name         159810 non-null  object
 4   club_position     159810 non-null  object
 5   club_joined_date  150272 non-null  object
 6   nationality_name  161583 non-null  object
 7   preferred_foot    161583 non-null  object
 8   work_rate         161583 non-null  object
 9   body_type         161583 non-null  object
 10  real_face         161583 non-null  object
 11  ls                161583 non-null  object
 12  st                161583 non-null  object
 13  rs                161583 non-null  object
 14  lw                161583 non-null  object
 15  lf                161583 non-null  object
 16  cf                161583 non-null  object
 17  rf                161583 non-null  object
 18  rw                161583 non-null  object
 19  lam               161583 non-null  object
 20  cam               161583 non-null  object
 21  ram               161583 non-null  object
 22  lm                161583 non-null  object
 23  lcm               161583 non-null  object
 24  cm                161583 non-null  object
 25  rcm               161583 non-null  object
 26  rm                161583 non-null  object
 27  lwb               161583 non-null  object
 28  ldm               161583 non-null  object
 29  cdm               161583 non-null  object
 30  rdm               161583 non-null  object
 31  rwb               161583 non-null  object
 32  lb                161583 non-null  object
 33  lcb               161583 non-null  object
 34  cb                161583 non-null  object
 35  rcb               161583 non-null  object
 36  rb                161583 non-null  object
 37  gk                161583 non-null  object
dtypes: object(38)
memory usage: 46.8+ MB

In [90]:
important_cols = ['preferred_foot', 'body_type']
cat.drop(columns = [column for column in cat.columns if column not in important_cols], inplace =True)

In [93]:
cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161583 entries, 0 to 161582
Data columns (total 2 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   preferred_foot  161583 non-null  object
 1   body_type       161583 non-null  object
dtypes: object(2)
memory usage: 2.5+ MB

In [95]:
#one hot encoding
cat = pd.get_dummies(cat).astype(int)
cat

,preferred_foot_Left,preferred_foot_Right,body_type_Lean (170-),body_type_Lean (170-185),body_type_Lean (185+),body_type_Normal (170-),body_type_Normal (170-185),body_type_Normal (185+),body_type_Stocky (170-),body_type_Stocky (170-185),body_type_Stocky (185+),body_type_Unique
0,1,0,0,0,0,1,0,0,0,0,0,0
1,0,1,0,0,0,0,0,1,0,0,0,0
2,1,0,0,0,0,0,1,0,0,0,0,0
3,0,1,0,0,0,0,0,1,0,0,0,0
4,0,1,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
161578,0,1,0,1,0,0,0,0,0,0,0,0
161579,1,0,0,0,0,0,0,1,0,0,0,0
161580,0,1,0,0,0,0,1,0,0,0,0,0
161581,0,1,0,0,0,0,1,0,0,0,0,0
161582,0,1,0,1,0,0,0,0,0,0,0,0

# USING ALL OUR DATA TO TRAIN AND TEST THE MODEL

In [97]:
# Handle categorical features using one-hot encoding
X = pd.get_dummies(X, drop_first=True)

# Fill missing values with the mean for numerical features
X.fillna(X.mean(), inplace=True)

# Standardize the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [98]:
# Split the training data into training and validation sets
X, X_val, Y, y_val = train_test_split(X, Y, test_size=0.2, random_state=42)

In [101]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
import numpy as np

In [103]:
# Initialize the ML models
models = {
    'Linear Regression': LinearRegression(),
    'Random Forest': RandomForestRegressor(),
    'Gradient Boosting': GradientBoostingRegressor()
}

In [105]:
linearmod=LinearRegression()
DeciderTree = DecisionTreeRegressor()
GradBoost = GradientBoostingRegressor()
RandFor = RandomForestRegressor()

In [107]:
# Evaluate models using cross-validation
results = {}
for name, model in models.items():
    scores = cross_val_score(model, X, Y, cv=5, scoring='neg_mean_squared_error')
    results[name] = np.sqrt(-scores.mean())

print("Model Evaluation Results:", results)

Model Evaluation Results: {'Linear Regression': 3.174721558355692e-14, 'Random Forest': 0.01018506156270855, 'Gradient Boosting': 0.006720133746413056}

In [108]:
with open('linear_model.pkl', 'wb') as file:
    pickle.dump(linearmod, file)  # Save the linear regression model

with open('GradBoost.pkl', 'wb') as file:
    pickle.dump(GradBoost, file)  # Save the regression model

with open('RandFor.pkl', 'wb') as file:
    pickle.dump(RandFor, file)  # Save the regression model

with open('DeciderTree.pkl', 'wb') as file:
    pickle.dump(DeciderTree, file)  # Save the regression model

params = {
    'n_estimators': [100,200,300],
    'max_depth': [5,7,9]
}

In [109]:
rando_search = RandomizedSearchCV(
    estimator=model,
    param_distributions=params,
    n_iter=9,  # Reduce number of iterations
    cv=2,  # Reduce number of cross-validation folds
    n_jobs=-1,  # Use all available cores
    random_state=42
)

In [ ]:
rando_search.fit(X, Y)

In [ ]:
best_model = rando_search.best_estimator_
best_model

In [ ]:
with open('best_model.pkl', 'wb') as file:
    pickle.dump(best_model, file)  # Save the regression model

In [ ]:
# Train the best model on the full training data and evaluate on the validation set
best_model.fit(X, Y)
y_pred = best_model.predict(X_val)
print("Validation RMSE:", np.sqrt(mean_squared_error(y_val, y_pred)))
best_model

In [ ]:
# Prepare the test data in a similar way
X_test = df2[relevant_columns]
X_test = pd.get_dummies(X_test, drop_first=True)
X_test.fillna(X_test.mean(), inplace=True)
X_test = scaler.transform(X_test)

# Predic the overall ratings for the test data
df2['predicted_overall'] = best_model.predict(X_test)

In [ ]:
# Save the predictions
df2.to_csv('predicted_players_22.csv', index=False)
print("Predictions saved to predicted_players_22.csv")

In [ ]:
#X = pd.concat([cat, quant], axis = 1)ta

In [ ]:
#Xtrain, Xtest, Ytrain, Ytest = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [ ]:
#from sklearn.linear_model import LinearRegression
#from sklearn.tree import DecisionTreeRegressor
#from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [ ]:
#lin_reg = LinearRegression()

In [120]:
#lin_reg.fit(Xtrain, Ytrain) #da training function
#lin_reg_pred = lin_reg.predict(Xtest)

In [121]:
#print(f""" Mean Aboslute Error={mean_absolute_error(lin_reg_pred,Ytest)}
          #Mean Squared Error = {mean_squared_error(lin_reg_pred,Ytest)}
          #Root Mean Squared error = {np.sqrt(mean_squared_error(lin_reg_pred,Ytest))}
          #R2 score = {r2_score(lin_reg_pred,Ytest)}
#""")

In [122]:
#dTree = DecisionTreeRegressor()
#dTree.fit(Xtrain, Ytrain)

In [123]:
#dTree_pred = dTree.predict(Xtest)

In [ ]:
#print(f""" Mean Aboslute Error={mean_absolute_error(dTree_pred,Ytest)}
          #Mean Squared Error = {mean_squared_error(dTree_pred,Ytest)}
          #Root Mean Squared error = {np.sqrt(mean_squared_error(dTree_pred,Ytest))}
          #R2 score = {r2_score(dTree_pred,Ytest)}
#""")

In [ ]:
#from sklearn.ensemble import RandomForestRegressor
#from sklearn.model_selection import RandomizedSearchCV

In [ ]:
#model = RandomForestRegressor()

In [ ]:
#parameter = {
    #'n_estimators': [100,200,300],
    #'max_depth': [5,7,9]
#}

In [ ]:
#rand_search = RandomizedSearchCV(model, parameter, scoring = 'r2', cv = 3)

In [ ]:
#rand_search.fit(Xtrain, Ytrain)

In [ ]:
# pickling the model 
#import pickle 
#pickle_out = open("classifier.pkl", "wb") 
#pickle.dump(classifier, pickle_out) 
#pickle_out.close()

In [ ]:
#!pip install streamlit